FORMAT: 1A
HOST: http://petrashenko.questium.local.samsonos.com/

# Questium API
[Questium](http://questium.com.ua) API documentation. All methods should receive regular POST oarameters.

## Show rooms collection [/api/showrooms/]

### Fetch all rooms [POST]


+ Attributes

    + url: questium (string, required) 
    

+ Request (application/x-www-form-urlencoded)
    
        url=questium

+ Response 200 (application/json)
    
    + Body
    
            {
                "rooms": [
                   
                        "Вечера на хуторе",
                        "Гавайская вечеринка",
                        "Ядерная угроза",
                        "1408"
                ],
                "result": 2
            }
            
            
## Show rooms collection [/api/showinfo/]

### Show room info request [POST]


+ Attributes

    + url: questium (string, required) 
    + room: gavajskaja-vecherinka (string, required)
    

+ Request (application/x-www-form-urlencoded)
    
        url=questium&room=gavajskaja-vecherinka

+ Response 200 (application/json)
    
    + Body
    
            {
                "rooms": [
                   
                        "Вечера на хуторе",
                        "Гавайская вечеринка",
                        "Ядерная угроза",
                        "1408"
                ],
                "result": 2
            }
            
## Show rooms collection [/api/showday/]

### Show day request [POST]


+ Attributes

    + url: questium (string, required) 
    + room: gavajskaja-vecherinka (string, required)
    + date: 2016-11-15 (string, required)

+ Request (application/x-www-form-urlencoded)
    
        url=questium&room=gavajskaja-vecherinka&date=2016-11-15

+ Response 200 (application/json)
    
    + Body
    
            {
                "rooms": [
                   
                        "Вечера на хуторе",
                        "Гавайская вечеринка",
                        "Ядерная угроза",
                        "1408"
                ],
                "result": 2
            }            

## Show rooms collection [/api/showhour/]

### Show room hour request [POST]


+ Attributes

    + url: questium (string, required) 
    + room: gavajskaja-vecherinka (string, required)
    + date: 2016-11-15 (string, required)
    + time: 15:00 (string, required)

+ Request (application/x-www-form-urlencoded)
    
        url=questium&room=gavajskaja-vecherinka&date=2016-11-15&time=15:00

+ Response 200 (application/json)
    
    + Body
    
            {
                "rooms": [
                   
                        "Вечера на хуторе",
                        "Гавайская вечеринка",
                        "Ядерная угроза",
                        "1408"
                ],
                "result": 2
            }            
            
## Show rooms collection [/api/showbooking/]

### Show room booking request [POST]


+ Attributes

    + url: questium (string, required) 
    + room: gavajskaja-vecherinka (string, required)

+ Request (application/x-www-form-urlencoded)
    
        url=questium&room=gavajskaja-vecherinka

+ Response 200 (application/json)
    
    + Body
    
            {
                "rooms": [
                   
                        "Вечера на хуторе",
                        "Гавайская вечеринка",
                        "Ядерная угроза",
                        "1408"
                ],
                "result": 2
            } 
            
## Show rooms collection [/api/bookinghour/]

### Create booking request [POST]


+ Attributes

    + url: questium (string, required) 
    + room: gavajskaja-vecherinka (string, required)
    + date: 2016-11-15 (string, required)
    + time: 15:00 (string, required)

+ Request (application/x-www-form-urlencoded)
    
        url=questium&room=gavajskaja-vecherinka&date=2016-11-15&time=15:00

+ Response 200 (application/json)
    
    + Body
    
            {
                "rooms": [
                   
                        "Вечера на хуторе",
                        "Гавайская вечеринка",
                        "Ядерная угроза",
                        "1408"
                ],
                "result": 2
            }