FORMAT: 1A
HOST: http://questium.com.ua/

# Questium API
[Questium](http://questium.com.ua) QUESTIUM API v1.0.0. Это API дает возможность просмотра расписания и бронирования времени посредством интерфейса QUESTIUM.
token - открытый ключ.Он высылается администратором сайта questium.com.ua.[param_token]
ARG_1...ARG_N - аргументы и их значения разные для разных методов
Все аргументы и ответ системы в формате UTF-8.
Ответ всех функции должен быть в формате json.


## Бронировка комнаты на сайте questium [/api/bookinghour/]

### Booking room [POST]


+ Attributes

    + url: zigraymo (string, required) 
    + room: palata-6 (string, required)
    + date: 19-01-2017 (string, required)
    + time: 11:10 (string, required)
    + price: 500 (number, required)
    + phone: 38XXXYYYYYYY (string, required)
    + comment: test (string, required)

+ Request (application/x-www-form-urlencoded)
    
        url=zigraymo&room=palata-6&date=19-01-2017&time=11:10&phone=38XXXYYYYYYY&comment=test&price=500

+ Response 200 (application/json)
    
    + Body
    
            {
                "room": "palata-6",
                "bookingDate": "19-01-2017",
                "bookingHour": "11:10",
                "price": "500"
            }
            
            
## Отображение состояния забронированных часов в пределах 10 дней от текущей даты. При реализации этой функции нужно учитывать время прекращение возможности бронирования до начала игры.   [/api/showbooking/]

### Show bookingHours [POST]


+ Attributes

    + url: zigraymo (string, required) 
    + room: palata-6 (string, required)
    

+ Request (application/x-www-form-urlencoded)
    
        url=zigraymo&room=palata

+ Response 200 (application/json)
    
    + Body
    
            {
                "room": "yadernaya-ugroza",
                "dateStart": "2016-12-15",
                "dateEnd": "2017-01-12",
                "dates": {
                    "2016-12-15": {
                        "dateFull": "15.12.2016",
                        "is_holiday": false,
                        "date": "2016-12-15",
                        "times": {
                            "10:00": {
                                "time": "10:00:00",
                                "price": "500",
                                "is_booked": "1"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "500",
                                "is_booked": "1"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "500",
                                "is_booked": "1"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "500",
                                "is_booked": "1"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "500",
                                "is_booked": "1"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "1"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    },
                    "2016-12-16": {
                        "dateFull": "16.12.2016",
                        "is_holiday": false,
                        "date": "2016-12-16",
                        "times": {
                                "10:00": {
                                "time": "10:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "1"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    },
                    "2016-12-17": {
                        "dateFull": "17.12.2016",
                        "is_holiday": true,
                        "date": "2016-12-17",
                        "times": {
                            "10:00": {
                                "time": "10:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    },
                    "2016-12-18": {
                        "dateFull": "18.12.2016",
                        "is_holiday": true,
                        "date": "2016-12-18",
                        "times": {
                            "10:00": {
                                "time": "10:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    },
                    "2016-12-19": {
                        "dateFull": "19.12.2016",
                        "is_holiday": false,
                        "date": "2016-12-19",
                        "times": {
                            "10:00": {
                                "time": "10:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    },
                    "2016-12-20": {
                        "dateFull": "20.12.2016",
                        "is_holiday": false,
                        "date": "2016-12-20",
                        "times": {
                            "10:00": {
                                "time": "10:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    },
                    "2016-12-21": {
                        "dateFull": "21.12.2016",
                        "is_holiday": false,
                        "date": "2016-12-21",
                        "times": {
                            "10:00": {
                                "time": "10:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "11:20": {
                                "time": "11:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "12:40": {
                                "time": "12:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "14:00": {
                                "time": "14:00:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "15:20": {
                                "time": "15:20:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "16:40": {
                                "time": "16:40:00",
                                "price": "500",
                                "is_booked": "2"
                            },
                            "18:00": {
                                "time": "18:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "19:20": {
                                "time": "19:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "20:40": {
                                "time": "20:40:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "22:00": {
                                "time": "22:00:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "23:20": {
                                "time": "23:20:00",
                                "price": "600",
                                "is_booked": "2"
                            },
                            "00:40": {
                                "time": "00:40:00",
                                "price": "600",
                                "is_booked": "2"
                            }
                        }
                    }
                }
            }
            

## Бронирование комнаты на других сайтах [/api/booking/]

### Booking room [POST]


+ Attributes

    + room: palata-6 (string, required)
    + date: 19-01-2017 (string, required)
    + time: 11:10 (string, required)
    + phone: 38XXXYYYYYYY (string, required)
    + comment: test (string, required)

+ Request (application/x-www-form-urlencoded)
    
        room=palata-6&date=19-01-2017&time=11:10&phone=38XXXYYYYYYY&comment=test

+ Response 200 (application/json)
    
    + Body
    
            {
                "room": "palata-6",
                "bookingDate": "19-01-2017",
                "bookingHour": "11:10",
                "price": "500"
            }